use crate::grade::GradeReport;
use crate::report::Severity;

pub fn export_markdown(report: &GradeReport) -> String {
    let mut md = String::new();

    md.push_str(&format!("# Luau Grader Report: {}\n\n", report.file));
    md.push_str(&format!("**Grade: {} ({:.0}/100)**  \n", report.grade, report.overall_score));
    md.push_str(&format!("**Tier:** {}  \n", report.tier));
    md.push_str(&format!("**Script Type:** {:?}  \n\n", report.script_type));

    md.push_str("## Dimension Scores\n\n");
    md.push_str("| Dimension | Score | Status |\n");
    md.push_str("|-----------|-------|--------|\n");
    for dim in &report.dimensions {
        let status = if dim.score >= 80 {
            "Good"
        } else if dim.score >= 60 {
            "Fair"
        } else {
            "Needs Work"
        };
        md.push_str(&format!("| {} | {} | {} |\n", dim.name, dim.score, status));
    }
    md.push('\n');

    if !report.function_grades.is_empty() {
        md.push_str("## Per-Function Grades\n\n");
        md.push_str("| Function | Line | Grade | Complexity | Lines |\n");
        md.push_str("|----------|------|-------|------------|-------|\n");
        for fg in &report.function_grades {
            md.push_str(&format!(
                "| {} | {} | {} | {} | {} |\n",
                fg.name, fg.line, fg.grade, fg.complexity, fg.lines
            ));
        }
        md.push('\n');
    }

    if !report.strengths.is_empty() {
        md.push_str("## Strengths\n\n");
        for s in &report.strengths {
            md.push_str(&format!("- {}\n", s));
        }
        md.push('\n');
    }

    if !report.improvement.fixes_needed.is_empty() {
        md.push_str("## Improvement Path\n\n");
        md.push_str(&format!(
            "**{} -> {}** (estimated {} minutes)\n\n",
            report.improvement.current_grade,
            report.improvement.projected_grade,
            report.improvement.effort_minutes
        ));
        for (i, fix) in report.improvement.fixes_needed.iter().enumerate() {
            md.push_str(&format!(
                "{}. **{}** (+{:.0} pts, ~{} min)\n",
                i + 1,
                fix.description,
                fix.score_impact,
                fix.effort_minutes
            ));
        }
        md.push('\n');
    }

    if report.debt.total_minutes > 0 {
        md.push_str("## Technical Debt\n\n");
        md.push_str(&format!(
            "**Total:** {} minutes\n\n",
            report.debt.total_minutes
        ));
        md.push_str("| Category | Time | Issues |\n");
        md.push_str("|----------|------|--------|\n");
        for item in &report.debt.breakdown {
            if item.minutes > 0 {
                md.push_str(&format!(
                    "| {} | {} min | {} |\n",
                    item.category, item.minutes, item.count
                ));
            }
        }
        md.push('\n');
    }

    if !report.diagnostics.is_empty() {
        let errors = report.diagnostics.iter().filter(|d| d.severity == Severity::Error).count();
        let warnings = report.diagnostics.iter().filter(|d| d.severity == Severity::Warning).count();
        let infos = report.diagnostics.iter().filter(|d| d.severity == Severity::Info).count();

        md.push_str("## Diagnostics\n\n");
        md.push_str(&format!(
            "**{} total** ({} errors, {} warnings, {} info)\n\n",
            report.diagnostics.len(),
            errors,
            warnings,
            infos
        ));

        md.push_str("| Rule | Severity | Line | Message |\n");
        md.push_str("|------|----------|------|---------|\n");
        for d in &report.diagnostics {
            let line = d
                .span
                .as_ref()
                .map(|s| s.line.to_string())
                .unwrap_or_default();
            let sev = format!("{:?}", d.severity);
            let msg = d.message.replace('|', "\\|");
            md.push_str(&format!("| {} | {} | {} | {} |\n", d.rule_id, sev, line, msg));
        }
        md.push('\n');
    }

    if !report.detected_patterns.is_empty() {
        md.push_str("## Detected Patterns\n\n");
        for p in &report.detected_patterns {
            md.push_str(&format!("- {}\n", p));
        }
        md.push('\n');
    }

    md.push_str("---\n*Generated by Luau Grader*\n");

    md
}
